### ISSUE TITLE
Merge RSAGA development efforts

### ISSUE THREAD

**Issue by pat-s** [stevenpawley/Rsagacmd#3] opened 2018-02-12 12:47 UTC
Hi Steven,

we (the development team of `RSAGA` including the maintainer Alexander Brenning, @jannes-m and @be-marc) recently came across your package.
While there have been no updates recently to the `RSAGA` package, we are currently working on a new CRAN version that supports all SAGA versions up to the most recent one. See https://github.com/be-marc/RSAGA. Also note that https://github.com/debangs/RSAGA is deprecated. 

I haven't yet taken a detailed look on the differences of your approach accessing the SAGA functions but I think it we could all save time by focusing on one SAGA interface for R instead having multiple ones out there.

You are very welcome to contribute to `RSAGA` and push it forward together with us :+1: 
We are not hesitant to also have a major version jump if some of your ideas are valuable for everyone and would require a rewrite of the code base.

Let us know what you think :smile: 

Cheers from the RSAGA team :duck:

**Comment by stevenpawley** [comment] 2018-02-12 20:23
Hi Patrick,

I agree that a single R-related SAGA-GIS package is ultimately more convenient and I'll fork RSAGA to look for options of integrating the two. At the moment, Rsagacmd emphasizes a different way to access SAGA-GIS than RSAGA, because my implementation is based on mapping every SAGA-GIS tool to an equivalent R function automatically. These functions are created dynamically, thus you don't need to worry about continuous maintenance for every new SAGA-GIS release. From using RSAGA, it appears that the user typically has to pass a list of arguments the saga.geoprocessor function, which requires you to know/look-up the exact syntax for each tool. I started work on Rsagacmd because I personally found this difficult, not on the part of RSAGA, but because of the inconsistent naming of arguments between related SAGA-GIS tools (e.g., ELEV, ELEVATION, DEM, INPUT, GRID etc.). In contrast in Rsagacmd, you access each function by generating a nested list of all of the tools in your installed version of SAGA, and access them like:

saga$ta_morphometry$Terrain_Ruggedness_Index_TRI(
    DEM=dem_clipped, RADIUS=r,
    TRI=file.path(outputdir, paste0('TRI', r, '_', dem_name, '.sgrd')))

This works nicely for example in Rstudio because you can autocomplete most of the arguments very quickly. I have also been working to make SAGA-GIS 'appear' like it is native R package, i.e. grids (RasterLayer objects), tables and shapefiles (spatial and sf objects) and passed back-and-forth behind the scenes. For convenience, non-optional outputs from SAGA-GIS are automatically saved to tempfiles if outputs are not explicitly stated, which means you can combine different tools with pipes, e.g.:

prj_bnd = st_read(file.path(projectdir, 'Basedata', 'AB_Permafrost_Model_Area.shp'))

pisr =  dem %>%
  saga$shapes_grid$Clip_Grid_with_Rectangle(SHAPES = prj_bnd)) %>%
  saga$grid_tools$Resampling(TARGET_USER_SIZE = 100) %>%
  saga$ta_lighting$Potential_Incoming_Solar_Radiation(
    LOCATION = 1, PERIOD = 2, DAY='2013-01-01', DAY_STOP = '2014-01-01',
    DAYS_STEP=10, HOUR_STEP=3, METHOD='Hofierka and Suri',
    GRD_LINKE_DEFAULT=3)

If required, temporary files can be cleaned during the session in a similar way to the raster package, using saga.removeTmpFiles(h=0).

I'm still working on some core features, specifically enabling grid tiling to be applied to any relevant SAGA-GIS function with the results being automatically mosaicked, and I need to do more testing, although overall I commonly use Rsagacmd for a fair part of my work.

In terms of integration, I think that I'll look to make sure that all of the core features are stable first, and then perhaps we can look for ways to integrate the two. One potential avenue is that Rsagacmd's initSAGA function, which returns a nested list of functions for every SAGA-GIS tool, is included within RSAGA, but the saga.geoprocessor can still be accessed in the traditional way as to ensure backwards compatibility.

Steve

**Comment by pat-s** [comment] 2018-02-12 22:11
Hi Steve,

thanks for the extensive reply!

That really sounds like a vast improvement in terms of usability! Also that fact that it makes the implementation unrelated to SAGA version problems (e.g. renaming of variables) is a huge benefit.

Native raster and sf handling is also great and the way to go, so +1 on this.

While surely we can only ask to combine the efforts into one package, it would also be a benefit for the spatial community). In that regard it is also worth mentioning the [r-spatial](https://github.com/r-spatial) org under which umbrella we could combine the efforts.

Backwards compatibility is of course always an issue but if major versions are released, it can be assumed that backwards compatibility is not guaranteed. Surely it would be great to combine both ways and also have the statistical helper functions from `RSAGA` in combination to the simple interface action to SAGA.  

The `initRSAGA` function sounds promising! Would it be ok for you to use functionality of your package in `RSAGA` already? As we are currently rewriting the automated detection of `saga_cmd` on all platforms, this could be really helpful.
Although we would of course credit you for this, we could certainly understand if you do not want that until your package is released to CRAN (if thats the plan) and the functions can be imported so you can get "full" credit for it.

**Comment by stevenpawley** [comment] 2018-02-16 21:32
Hi Patrick,

At the moment, I am still developing the package, which might include some potential structural changes to the code and interface, so I still have some work before it is 'stable' from a user's perspective. My plan was then to submit to CRAN, so probably right now the fastest way of integration would be to just import those functions once it is released. However, overall I'm certainly not opposed to integrating the two packages, I would just rather focus on developing/completing the new functionality first (which relates to my own research/mapping needs), before looking to integrate. Some functionality is shared between the two packages, i.e. Rsagacmd has an equivalent of RSAGA's saga.geoprocessor function, but in Rsagacmd this function is designed to be called by the dynamically generated functions, and internally works in a somewhat different way. Probably in the future, uniting these two functions would then allow both packages to be merged quite easily.

Of course there is also the link2GI package which includes a method to automatically detect saga_cmd on all platforms, so in a sense there is any some potential scope for integrating at least parts of that package as well, either internally or by importing its functions.

**Comment by gisma** [comment] 2018-02-19 22:19
Hi Steven,
the link2GI package is not doing so much at all. If you join your both approaches and include a SAGA version selection similar as you basically have already implemented there will be no need to use the `linkSaga` function. Originally it was designed to simplify the CLI calls of SAGA GIS and just as a side effect to set the system variables for `RSAGA`. Calling SAGA via pure system calls will be obsolete then and I will mark the SAGA stuff as  deprecated.

**Closed as completed** 2018-03-27 05:50 UTC
